- name: Install homelab
  hosts: servers
  become: true
  vars_files:
    - ../secret.yml

  tasks:
    - name: Check if directory KubePods exist
      ansible.builtin.stat:
        path: homelab/
      register: homelab_directory

    - name: Clone KubePods directory
      ansible.builtin.git:
        repo: https://github.com/TimotheeRen/homelab
        dest: homelab
      when: not homelab_directory.stat.exists

    - name: Check if K3d cluster exists
      ansible.builtin.command:
        cmd: k3d cluster list Homelab
      register: k3d_check
      failed_when: false
      changed_when: false
      become: false

    - name: Create K3d Cluster
      ansible.builtin.command:
        cmd: k3d cluster create --config homelab/k3d/config.yaml -p "8080:80@loadbalancer" -p "32021:32021@server:0"
      when: k3d_check.rc != 0
      become: false
    - name: Install Flux Operator
      ansible.builtin.command:
        cmd: >
          helm upgrade --install flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
          --namespace flux-system
          --create-namespace
      become: false

    - name: Create homelab's cluster
      ansible.builtin.command:
        cmd: kubectl apply -f homelab/flux-instance.yaml
      become: false
