apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution: 
    version: "2.8.6"
    registry: "ghcr.io/fluxcd"
  cluster:
    size: small
  sync:
    kind: GitRepository
    url: "https://github.com/TimotheeRen/homelab"
    ref: "refs/heads/main"
    path: "fluxcd/clusters/dev"
