apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: nextcloud
      version: "9.2.2"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 10m
  values:
    service:
      type: NodePort
      nodePort: 32080
      port: 8080
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "nextcloud-postgres-cluster-rw"
      port: 5432
      database: "app"
      existingSecret:
        enabled: true
        secretName: "nextcloud-postgres-cluster-app"
        usernameKey: "username"
        passwordKey: "password"
    nextcloud:
      trustedDomains:
        - nextcloud.kube.home
        - 192.168.1.59
        - localhost
