- ansible.builtin.import_playbook: playbooks/setup.yml
  tags: setup
- ansible.builtin.import_playbook: playbooks/install-homelab.yml
  tags: setup
- ansible.builtin.import_playbook: playbooks/post-install.yml
  tags: post-install
